# Generated by Django 4.0.5 on 2022-06-28 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_coder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='villa_olimpica',
            name='imagen',
            field=models.ImageField(null=True, upload_to='villa'),
        ),
    ]
