# Generated by Django 4.0.5 on 2022-06-28 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_coder', '0002_villa_olimpica_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='villa_olimpica',
            name='imagen',
        ),
    ]
